"""Breed trait auxiliary heads (training-only).

Traits are free-form string fields per breed (see ``data/breed_traits.json``,
generated by ``scripts/make_trait_template.py``). For each field we build a
vocabulary from the distinct non-empty values and train a small classifier on
the pooled backbone features, using the breed label to derive per-sample trait
targets. Empty values are ignored by the masked loss.

These heads are auxiliary: they are NOT part of ``BreedClassifier.forward`` and
are excluded from export. They are attached to the model in ``train.py`` only
when ``--trait-weight > 0``.
"""

import json
import os

import torch
import torch.nn as nn
import torch.nn.functional as F

from .config import NUM_BUFFALO_BREEDS, NUM_CATTLE_BREEDS


def load_trait_spec(path):
    if not path or not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def build_trait_vocab(spec):
    """{field: {value: index}} for fields that have at least one filled value."""
    if not spec:
        return {}
    vocab = {}
    for field in spec.get("fields", []):
        values = set()
        for species in ("cattle", "buffalo"):
            for _breed, tv in spec.get("breeds", {}).get(species, {}).items():
                v = (tv.get(field) or "").strip()
                if v:
                    values.add(v)
        if values:
            vocab[field] = {v: i for i, v in enumerate(sorted(values))}
    return vocab


def breed_trait_targets(spec, vocab, cattle_classes, buffalo_classes):
    """Per-field LongTensor[75]: global class id -> trait index, or -1 to ignore.

    Global ids follow ``_combined_class_ids``: cattle 0..NUM_CATTLE-1, buffalo
    NUM_CATTLE..NUM_CATTLE+NUM_BUFFALO-1. The tensor is always sized to the
    fixed head size (75) so it covers every possible global id.
    """
    n = NUM_CATTLE_BREEDS + NUM_BUFFALO_BREEDS
    targets = {f: torch.full((n,), -1, dtype=torch.long) for f in vocab}
    for species, cmap, offset in (("cattle", cattle_classes, 0),
                                  ("buffalo", buffalo_classes, NUM_CATTLE_BREEDS)):
        for breed, idx in cmap.items():
            tv = spec.get("breeds", {}).get(species, {}).get(breed, {})
            for field in vocab:
                val = (tv.get(field) or "").strip()
                if val in vocab[field]:
                    targets[field][offset + idx] = vocab[field][val]
    return targets


class TraitClassifier(nn.Module):
    def __init__(self, in_dim, vocab, hidden=256, dropout=0.2):
        super().__init__()
        self.vocab = vocab
        self.fields = list(vocab.keys())
        self.heads = nn.ModuleDict({
            field: nn.Sequential(
                nn.Linear(in_dim, hidden),
                nn.ReLU(inplace=True),
                nn.Dropout(dropout),
                nn.Linear(hidden, len(vocab[field])),
            )
            for field in self.fields
        })

    def forward(self, features):
        return {field: self.heads[field](features) for field in self.fields}

    def loss(self, features, class_ids, targets, label_smoothing=0.0):
        """Masked multi-field CE. Returns (mean_loss, {field: acc})."""
        logits = self.forward(features)
        total = features.new_zeros(())
        n_fields = 0
        accs = {}
        for field in self.fields:
            tgt = targets[field].to(class_ids.device)[class_ids]
            valid = tgt >= 0
            if not valid.any():
                continue
            total = total + F.cross_entropy(logits[field][valid], tgt[valid],
                                            label_smoothing=label_smoothing)
            n_fields += 1
            accs[field] = (logits[field][valid].argmax(1) == tgt[valid]).float().mean().item()
        if n_fields:
            total = total / n_fields
        return total, accs


@torch.no_grad()
def evaluate_traits(model, trait_module, loader, targets, device,
                    max_batches=None):
    """Per-field accuracy over a loader (soft/hard-agnostic; uses features)."""
    from .train import _combined_class_ids
    trait_module.eval()
    totals = {f: [0, 0] for f in trait_module.fields}
    for step, (images, labels) in enumerate(loader):
        if max_batches is not None and step >= max_batches:
            break
        images = images.to(device)
        labels = {k: v.to(device) for k, v in labels.items()}
        feats = model(images)["features"]
        ids = _combined_class_ids(labels)
        logits = trait_module(feats)
        for field in trait_module.fields:
            tgt = targets[field].to(device)[ids]
            valid = tgt >= 0
            if valid.any():
                totals[field][0] += (logits[field][valid].argmax(1)
                                     == tgt[valid]).sum().item()
                totals[field][1] += int(valid.sum())
    return {f: (c / n if n else None) for f, (c, n) in totals.items()}
